campaigns/urls.py
from django.urls import path

from .views import home,detail,results,vote,resultsData

app_name = 'campaigns'
urlpatterns = [
    path('',   home, name='home'),
    path('<int:campaign_id>/',   detail, name='campaign_detail'),
    path('<int:campaign_id>/results/',   results, name='campaign_results'),
    path('<int:campaign_id>/vote/',   vote, name='campaign_vote'),
    path('resultsdata/<str:obj>/',   resultsData, name='campaign_resultsdata'),
]

e-voting/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('campaigns/', include('campaigns.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('resultsdata/<str:obj>/', views.resultsData, name='resultsdata'),
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
from django.db import models
from django.contrib.auth.models import User


class Campaign(models.Model):
    campaign_text = models.CharField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)
    candidates = models.ManyToManyField(User,related_name='campaign_candidates')
    voters = models.ManyToManyField(User,related_name='campaign_voters')

    def __str__(self):
        return self.campaign_text

class CampaignVote(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    candiate = models.ForeignKey(User, on_delete=models.CASCADE,related_name='campaignvote_candiate')
    voter = models.ForeignKey(User, on_delete=models.CASCADE,related_name='campaignvote_voter')
    created_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table='campaign_vote'

campaigns/forms.py
from django import forms
from .models import Campaign

class CampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign

campaigns/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Campaign, CampaignVote
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db import transaction
from users.models import User

from django.db.models import Count

# Get campaigns and display them
@login_required
def home(request):
    campaign_queryset = Campaign.objects.filter(voters=request.user).order_by('-created_on')
    context = {'campaign_queryset': campaign_queryset,'len':len(campaign_queryset)}
    return render(request, 'campaigns/index.html', context)

# Show specific campaign and choices
@login_required
def detail(request, campaign_id):
  try:
    campaign = Campaign.objects.get(pk=campaign_id)
  except Campaign.DoesNotExist:
    raise Http404("Campaign does not exist")
  return render(request, 'campaigns/detail.html', { 'campaign': campaign })

# Get campaign and display results
@login_required
def results(request, campaign_id):
  result={}
  campaign = get_object_or_404(Campaign, pk=campaign_id)
  for i in CampaignVote.objects.filter(campaign=campaign):
     if i.candiate.username in result:
        result[i.candiate.username]+=1
     else:
        result[i.candiate.username]=1
  print(result)

  return render(request, 'campaigns/results.html', { 'campaign': campaign ,'result':result})

# Vote for a campaign choice
@login_required
def vote(request, campaign_id):
    # print(request.POST['choice'])
    campaign = get_object_or_404(Campaign, pk=campaign_id)
    if CampaignVote.objects.filter(voter=request.user,campaign=campaign).exists():
       return render(request, 'campaigns/detail.html', {
            'campaign': campaign,
            'error_message': "Already gave the vote.",
        })
    try:
        selected_choice = campaign.candidates.get(pk=request.POST['choice'])
    except (KeyError, User.DoesNotExist):
        # Redisplay the campaign voting form.
        return render(request, 'campaigns/detail.html', {
            'campaign': campaign,
            'error_message': "You didn't select a choice.",
        })
    if selected_choice == request.user:
       return render(request, 'campaigns/detail.html', {
            'campaign': campaign,
            'error_message': "Cant Vote for Yourself",
        })
    else:
        try:
          with transaction.atomic():
            CampaignVote.objects.create(voter=request.user,campaign=campaign,candiate=selected_choice)
        except Exception as err:
           return render(request, 'campaigns/detail.html', {
            'campaign': campaign,
            'error_message': "Problem in DataBase",
        })

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('campaigns:campaign_results', args=(campaign.id,)))

@login_required
def resultsData(request, obj):
    print("Coming Here")
    votedata = []
    campaign = Campaign.objects.get(id=obj)
    print(campaign)
    try:
      votes=CampaignVote.objects.filter(campaign=campaign).values('candiate','id').aggregate(Count(id))
    except Exception as err:
       print(err)
    print(votes)

    for i in votes:
        votedata.append({i.choice_text:i.votes})

    # return JsonResponse(votedata, safe=False)

templates/campaigns/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'campaigns:home' %}">Back To campaigns</a>
<h1 class="text-center mb-3">{{ campaign.campaign_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'campaigns:campaign_vote' campaign.id %}" method="post">
	{% csrf_token %} 
	{% for choice in campaign.candidates.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.username }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/campaigns/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center mb-3">Poll Campaigns</h1>
  Number of Campagins for User: {{ len }}
  {% if campaign_queryset %}
    {% for campaign in campaign_queryset %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ campaign.campaign_text }}</p>
          <a href="{% url 'campaigns:campaign_detail' campaign.id %}" class="btn btn-primary btn-sm">Vote Now</a>
          <a href="{% url 'campaigns:campaign_results' campaign.id %}" class="btn btn-secondary btn-sm">Results</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No campaigns available</p>
  {% endif %}
{% endblock %}

templates/campaigns/results.html
{% extends 'base.html' %}
{% block content %}

<h1 class="mb-5 text-center">{{ campaign.campaign_text }}</h1>

<ul class="list-group mb-5">
	{% for key, value in result.items %}
	<li class="list-group-item">
		{{ key }}  <span class="badge badge-success float-right">{{ value }} vote{{ value | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<div class="mb-4 mx-4">
<a class="btn btn-info ml-4" href="{% url 'campaigns:home' %}">Back To campaigns</a>
</div>

{% endblock %}